# -*- coding: utf-8 -*-
"""resume classifier project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZiUnqKTZbPl4QJPqF-EI5lLhuuu7gOo
"""

# ----------- 1. Import Required Libraries -----------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import label_binarize
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)
import zipfile
import os

# Optional (for PDF / Image resumes)
!pip install pytesseract
!pip install PyPDF2
from PIL import Image
import pytesseract
import PyPDF2

import pandas as pd

# -----------------------------------------------
# 2. Load First Dataset
# -----------------------------------------------

url = "https://media.githubusercontent.com/media/noran-mohamed/Resume-Classification-Dataset/refs/heads/main/Preprocessed_Data.csv"
data = pd.read_csv(url)

# -----------------------------------------------
# Load Second Resume Dataset (CSV only)
# -----------------------------------------------

csv_path = "/content/sample_data/Resume.csv"  # <-- update this path to your CSV file

data2 = pd.read_csv(csv_path)

# Normalize columns
data2 = data2.rename(columns={
    "Resume_str": "Resume"
})

# Keep only required columns
data2 = data2[["Category", "Resume"]]

# Clean Resume column
data2["Resume"] = data2["Resume"].astype(str).fillna("")

# Filter technical categories
TECH_CATEGORIES = [
    "INFORMATION-TECHNOLOGY",
    "SOFTWARE",
    "ENGINEERING",
    "DATA SCIENCE",
    "DEVOPS",
    "DATABASE",
    "AI",
    "ML"
]

data2 = data2[data2["Category"].str.upper().isin(TECH_CATEGORIES)]

# Sample dataset
data2 = data2.sample(frac=0.5, random_state=42).reset_index(drop=True)

# Rename & clean columns
data = data.rename(columns={'Text': 'Resume'})
data = data[['Category', 'Resume']]
data['Resume'] = data['Resume'].astype(str).fillna("")

print("Dataset Loaded Successfully")


# -----------------------------------------------
# ADDITION: Normalize category labels
# -----------------------------------------------

for df in [data, data2]:
    df["Category"] = (
        df["Category"]
        .str.strip()
        .str.lower()
    )
print("\nDataset 1 (after normalization):")
print(data.head())

print("\nDataset 2 (after normalization):")
print(data2.head())

# -----------------------------------------------
# ADDITION: Merge both datasets
# -----------------------------------------------

data = pd.concat([data, data2], ignore_index=True)


print("Total resumes:", len(data))
print("Unique categories:", data["Category"].nunique())

CATEGORY_MAP = {
    "data science": "data_science",
    "datascience": "data_science",
    "ml engineer": "data_science",
    "machine learning": "data_science",

    "software engineer": "software_developer",
    "software developer": "software_developer",
    "developer": "software_developer",

    "devops engineer": "devops",
    "cloud engineer": "devops",

    "network security engineer": "cybersecurity",
    "cyber security": "cybersecurity",
}

data["Category"] = data["Category"].replace(CATEGORY_MAP)

# -----------------------------------------------
# 3. Train-Test Split
# -----------------------------------------------

X = data['Resume']
y = data['Category']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# -----------------------------------------------
# 4. TF-IDF Vectorizer [COMMENTED OUT - OLD]
# -----------------------------------------------

tfidf = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    max_features=25000,
    min_df=5,
    sublinear_tf=True
)
print("TF-IDF Vectorizer Initialized")

# -----------------------------------------------
# 5. Models Definition
# -----------------------------------------------

from sklearn.calibration import CalibratedClassifierCV

models = {
    "Logistic Regression": CalibratedClassifierCV(
        LogisticRegression(max_iter=1000),
        method="sigmoid"
    ),
    "Random Forest": CalibratedClassifierCV(
        RandomForestClassifier(n_estimators=200, random_state=42),
        method="sigmoid"
    ),
    "Linear SVM": CalibratedClassifierCV(
        LinearSVC(),
        method="sigmoid"
    )
}
print("Models Initialized")
results = {}

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_curve,
    auc
)
from sklearn.preprocessing import label_binarize

# -----------------------------------------------
# 6. Model Training & Evaluation (COLOURFUL)
# -----------------------------------------------

categories = sorted(y.unique())
y_test_bin = label_binarize(y_test, classes=categories)

results = {}

# Figure for combined ROC curves
plt.figure(figsize=(9, 7))

for name, model in models.items():
    print("\n" + "="*70)
    print(f"Training & Evaluating: {name}")
    print("="*70)

    # Pipeline
    pipeline = make_pipeline(tfidf, model)
    pipeline.fit(X_train, y_train)


    # Predictions
    y_pred = pipeline.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    results[name] = {
        "model": pipeline,
        "accuracy": acc
    }

    print(f"\nAccuracy: {acc:.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=categories))

    # -------------------------------
    # Confusion Matrix (Colourful)
    # -------------------------------
    cm = confusion_matrix(y_test, y_pred, labels=categories)

    plt.figure(figsize=(14, 12))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="viridis",
        linewidths=0.5,
        linecolor="white",
        xticklabels=categories,
        yticklabels=categories
    )
    plt.title(f"{name} – Confusion Matrix", fontsize=16, fontweight="bold")
    plt.xlabel("Predicted Label", fontsize=12)
    plt.ylabel("True Label", fontsize=12)
    plt.xticks(rotation=90)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    # -------------------------------
    # ROC Curve (Micro-Average)
    # -------------------------------
    if hasattr(pipeline.named_steps[list(pipeline.named_steps.keys())[-1]], "predict_proba"):
        y_score = pipeline.predict_proba(X_test)
    else:
        # For Linear SVM
        y_score = pipeline.decision_function(X_test)

    fpr, tpr, _ = roc_curve(y_test_bin.ravel(), y_score.ravel())
    roc_auc = auc(fpr, tpr)

    plt.plot(
        fpr,
        tpr,
        linewidth=3,
        label=f"{name} (AUC = {roc_auc:.3f})"
    )

# -------------------------------
# Final ROC Curve Styling
# -------------------------------
plt.plot([0, 1], [0, 1], linestyle="--", color="gray", linewidth=2)
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.title("ROC Curve Comparison (Micro-Average)", fontsize=16, fontweight="bold")
plt.legend(loc="lower right", fontsize=11)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

model_names = list(results.keys())
accuracies = [results[m]["accuracy"] for m in model_names]

plt.figure(figsize=(8, 6))
sns.barplot(
    x=model_names,
    y=accuracies,
    palette="Set2"
)

plt.title("Model Accuracy Comparison", fontsize=16, fontweight="bold")
plt.ylabel("Accuracy")
plt.xlabel("Model")
plt.ylim(0.7, 1.0)

for i, v in enumerate(accuracies):
    plt.text(i, v + 0.005, f"{v:.3f}", ha="center", fontsize=11)

plt.tight_layout()
plt.show()

# -----------------------------------------------
# 8. Select Best Model (Highest Accuracy)
# -----------------------------------------------

best_model_name = max(results, key=lambda x: results[x]["accuracy"])
best_model = results[best_model_name]["model"]

print(f"\nBest Model Selected: {best_model_name}")

# -----------------------------------------------
# 9. Train Best Model on Full Dataset
# -----------------------------------------------

best_model.fit(X, y)

# Save model
joblib.dump(best_model, "resume_classifier_model.pkl")
print("Best Model Saved Successfully")

# -----------------------------------------------
# 10. Resume Text Extraction Functions
# -----------------------------------------------

def extract_text_from_pdf(file_path):
    text = ""
    with open(file_path, "rb") as f:
        reader = PyPDF2.PdfReader(f)
        for page in reader.pages:
            text += page.extract_text()
    return text

def extract_text_from_image(file_path):
    image = Image.open(file_path)
    return pytesseract.image_to_string(image)

# -----------------------------------------------
# 11. Resume Prediction Functions
# -----------------------------------------------

import joblib
import numpy as np

def predict_with_confidence(text):
    """
    Predict resume category with confidence score
    """
    model = joblib.load("resume_classifier_model.pkl")

    # Prediction
    prediction = model.predict([text])[0]

    # Confidence
    final_model = model.named_steps[list(model.named_steps.keys())[-1]]

def predict_with_confidence(text):
    model = joblib.load("resume_classifier_model.pkl")

    probs = model.predict_proba([text])[0]
    classes = model.classes_

    predicted_index = np.argmax(probs)
    prediction = classes[predicted_index]

    confidence = probs[predicted_index] * 100

    return prediction, confidence

def confidence_label(confidence):
    if confidence >= 85:
        return "Very High"
    elif confidence >= 70:
        return "High"
    elif confidence >= 50:
        return "Moderate"
    else:
        return "Low"

# -----------------------------------------------
# 12. Upload Resume from Computer (Google Colab)
# -----------------------------------------------

import os
import google.colab.files

def upload_resume_colab():
    """
    Upload resume file from computer in Colab
    Supports: .txt, .pdf, .png, .jpg, .jpeg
    """
    uploaded = google.colab.files.upload()

    if not uploaded:
        raise ValueError("No file uploaded.")

    file_name = list(uploaded.keys())[0]
    temp_path = f"/content/{file_name}"

    # Save uploaded file
    with open(temp_path, "wb") as f:
        f.write(uploaded[file_name])

    # Extract text
    if temp_path.lower().endswith(".txt"):
        with open(temp_path, "r", encoding="utf-8", errors="ignore") as f:
            resume_text = f.read()

    elif temp_path.lower().endswith(".pdf"):
        resume_text = extract_text_from_pdf(temp_path)

    elif temp_path.lower().endswith((".png", ".jpg", ".jpeg")):
        resume_text = extract_text_from_image(temp_path)

    else:
        os.remove(temp_path)
        raise ValueError("Unsupported file format")

    os.remove(temp_path)
    return resume_text


# -----------------------------------------------
# 13. Run Resume Classification
# -----------------------------------------------

try:
    resume_text = upload_resume_colab()

    category, confidence = predict_with_confidence(resume_text)

    print("\nPredicted Career Category:", category)
    print(f"Confidence Score: {confidence:.2f}% ({confidence_label(confidence)})")


except Exception as e:
    print("Error:", e)